### ISSUE TITLE
Questions about the API key

### ISSUE THREAD

**Issue by tide29** [ProjectDossier/sdp2022#24]
Hello,

I apologize for the interruption. I am a student majoring in Big Data, and our teacher has assigned us a task to read and implement the methods described in a research paper. Our group is particularly interested in the paper titled "Benchmark for Research Theme Classification of Scholarly Documents." However, we encountered some confusion with parts of the code after cloning your repository. Despite spending an entire day on it, we haven't been able to achieve the correct results. Specifically, we are puzzled about the `api_key` mentioned in the code. 

We are also not very familiar with using GitHub and hope you can point out our mistakes.

We are unsure of your time zone, and we apologize if this message reaches you at an inconvenient time.
![e7384538ea1d0ad25c39f6a5804c3c4](https://github.com/ProjectDossier/sdp2022/assets/99459306/854ff9dc-38eb-4118-ac9f-3b574fc1d3b3)

**Comment by WojciechKusa** [comment]
Hi @tide29,

Thank you for reaching out.

To use the CORE API mentioned in the code, you first need to register and obtain an API key. You can do this by visiting the following link: [CORE API](https://core.ac.uk/services/api). Once registered, you'll receive an API key that you can place in the `api_key.txt` file.

Here are the steps you need to follow:

1. Go to the [CORE API Registration](https://core.ac.uk/services/api#what-is-included) page.
2. Sign up for an account and apply for an API key.
3. Once you receive your API key, create a file named `api_key.txt` in the `../data/` directory of your project.
4. Paste the API key into this file and save it.
5. After completing these steps, your code should be able to read the API key correctly and proceed without the `FileNotFoundError`.

If you have any further questions or run into any other issues, feel free to ask.

Best,
Wojciech

**Comment by tide29** [comment]
Hi，Sincerely thank you for your reply, 

I will try your suggestion as soon as possible. Thank you so much
